name: bridge

services:
  frontend:
    image: alpine:latest
    container_name: frontend
    command: sh -c "while :; do echo 'Container is running'; sleep 3600; done"
    networks:
      bridge:
        ipv4_address: 192.168.20.20

  backend:
    image: alpine:latest
    container_name: backend
    command: sh -c "while :; do echo 'Container is running'; sleep 3600; done"
    networks:
      bridge:
        ipv4_address: 192.168.20.10
        
  database:
    image: alpine:latest
    container_name: database
    command: sh -c "while :; do echo 'Container is running'; sleep 3600; done"
    networks:
      bridge:
        ipv4_address: 192.168.10.10

networks:
  bridge:
    ipam: # meaning IP Address Management
      driver: default # default is bridge
      config:
        - subnet: 192.168.0.0/16

# docker-compose -f src/ipam.yml up -d
# docker-compose -f src/ipam.yml down

